### ISSUE TITLE
jre9及以上版本提示找不到类sun/misc/BASE64Encode

### ISSUE THREAD

**Issue by guerlab** [tencentyun/tls-sig-api-v2-java#1]
Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder
	at com.tencentyun.TLSSigAPIv2.hmacsha256(TLSSigAPIv2.java:40)
	at com.tencentyun.TLSSigAPIv2.genSig(TLSSigAPIv2.java:66)
	at com.tencentyun.TLSSigAPIv2.genSig(TLSSigAPIv2.java:81)

9.0及以上版本弃用了sun.misc.BASE64Encode

**Comment by weijunyi** [comment]
新版本可以尝试先修改代码，手动本地构建 jar 包，这个问题我们后续跟进解决。

**Comment by Ray-Sir-Like** [comment]
> 新版本可以尝试先修改代码，手动本地构建 jar 包，这个问题我们后续跟进解决。

什么时候改进呢？我现在使用JDK11版本，提示tjava.lang.NoClassDefFoundError: sun/misc/BASE64Encoder

**Comment by CodingOX** [comment]
> 新版本可以尝试先修改代码，手动本地构建 jar 包，这个问题我们后续跟进解决。

建议及时处理，JDK11 应该很快会上来了！

**Comment by wanghongenpin** [comment]
JDK15已经发布

**Comment by guerlab** [comment]
有没有一种感觉已经放弃更新的感觉？？？？

**Comment by CodingOX** [comment]
懒得提 pr 了，可以通过 `java.util.Base64` 进行替换，这个给一个参照，大家自行测试下，我通过腾讯云 TRTC的那个网页工具测试了，没有问题！
```java
public class Base64URL {

    public static byte[] base64EncodeUrl(byte[] input) {
        byte[] base64 = Base64.getEncoder().encode(input);
        for (int i = 0; i < base64.length; ++i)
            switch (base64[i]) {
                case '+':
                    base64[i] = '*';
                    break;
                case '/':
                    base64[i] = '-';
                    break;
                case '=':
                    base64[i] = '_';
                    break;
                default:
                    break;
            }
        return base64;
    }

    public static byte[] base64DecodeUrl(byte[] input) throws IOException {
        byte[] base64 = input.clone();
        for (int i = 0; i < base64.length; ++i)
            switch (base64[i]) {
                case '*':
                    base64[i] = '+';
                    break;
                case '-':
                    base64[i] = '/';
                    break;
                case '_':
                    base64[i] = '=';
                    break;
                default:
                    break;
            }
        return Base64.getDecoder().decode(new String(base64));
    }
}
```

关键类：
``` java
import com.alibaba.fastjson.JSONObject;

import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import java.nio.charset.StandardCharsets;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.util.Arrays;
import java.util.Base64;
import java.util.zip.Deflater;


public class TLSSigAPIv2 {
    private final long sdkappid;
    private final String key;

    public TLSSigAPIv2(long sdkappid, String key) {
        this.sdkappid = sdkappid;
        this.key = key;
    }

    private String hmacsha256(String identifier, long currTime, long expire, String base64Userbuf) {
        String contentToBeSigned = "TLS.identifier:" + identifier + "\n"
                + "TLS.sdkappid:" + sdkappid + "\n"
                + "TLS.time:" + currTime + "\n"
                + "TLS.expire:" + expire + "\n";
        if (null != base64Userbuf) {
            contentToBeSigned += "TLS.userbuf:" + base64Userbuf + "\n";
        }
        try {
            byte[] byteKey = key.getBytes(StandardCharsets.UTF_8);
            Mac hmac = Mac.getInstance("HmacSHA256");
            SecretKeySpec keySpec = new SecretKeySpec(byteKey, "HmacSHA256");
            hmac.init(keySpec);
            byte[] byteSig = hmac.doFinal(contentToBeSigned.getBytes(StandardCharsets.UTF_8));
            return (Base64.getEncoder().encodeToString(byteSig)).replaceAll("\\s*", "");
        } catch (NoSuchAlgorithmException e) {
            return "";
        } catch (InvalidKeyException e) {
            return "";
        }
    }

    private String genSig(String identifier, long expire, byte[] userbuf) {

        long currTime = System.currentTimeMillis() / 1000;

        JSONObject sigDoc = new JSONObject();
        sigDoc.put("TLS.ver", "2.0");
        sigDoc.put("TLS.identifier", identifier);
        sigDoc.put("TLS.sdkappid", sdkappid);
        sigDoc.put("TLS.expire", expire);
        sigDoc.put("TLS.time", currTime);

        String base64UserBuf = null;
        if (null != userbuf) {
            base64UserBuf = Base64.getEncoder().encodeToString(userbuf);
            sigDoc.put("TLS.userbuf", base64UserBuf);
        }
        String sig = hmacsha256(identifier, currTime, expire, base64UserBuf);
        if (sig.length() == 0) {
            return "";
        }
        sigDoc.put("TLS.sig", sig);
        Deflater compressor = new Deflater();
        compressor.setInput(sigDoc.toString().getBytes(StandardCharsets.UTF_8));
        compressor.finish();
        byte[] compressedBytes = new byte[2048];
        int compressedBytesLength = compressor.deflate(compressedBytes);
        compressor.end();
        return (new String(Base64URL.base64EncodeUrl(Arrays.copyOfRange(compressedBytes,
                0, compressedBytesLength)))).replaceAll("\\s*", "");
    }

    public String genSig(String identifier, long expire) {
        return genSig(identifier, expire, null);
    }

    public String genSigWithUserBuf(String identifier, long expire, byte[] userbuf) {
        return genSig(identifier, expire, userbuf);
    }
}
```
上面那个`JSONObject` 我用的是 fastjson 的。
目前在 JDK11 上是 ok的。

**Comment by llwmeme** [comment]
同样遇到了以上的问题，希望尽快修复。

**Comment by weijunyi** [comment]
请直接使用 v2.0。

**Comment by peterrrLiu** [comment]
jakarta.servlet.ServletException: Handler dispatch failed: java.lang.NoClassDefFoundError: com/tencentyun/TLSSigAPIv2
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1104) ~[spring-webmvc-6.1.15.jar:6.1.15]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979) ~[spring-webmvc-6.1.15.jar:6.1.15]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-6.1.15.jar:6.1.15]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903) ~[spring-webmvc-6.1.15.jar:6.1.15]


JDK17，咋抛出了这个错误呢
